name: Banking App CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Add these services so the tests have a DB to talk to
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin123
          MYSQL_DATABASE: securebank
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Copy Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build & Test
        # We pass the Env Variables here so Maven can see them
        env:
          DB_URL: jdbc:mysql://localhost:3306/securebank
          DB_USER: root
          DB_PASSWORD: admin123
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: mvn clean verify

      # ... (Login and Push steps remain the same)